spring:
  datasource:
    url: jdbc:mysql://120.77.45.136:3306/wms?characterEncoding=UTF-8&nullCatalogMeansCurrent=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    username: anymre
    password: c1234567
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml


pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  helper-dialect: mysql
